### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by HowardZHY** [HowardZHY/CustomSkinLoader-LegacyFabric#1]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-11-16 02:19:01 SGT
Description: Unexpected error

java.lang.ClassCastException: customskinloader.fake.FakeSkinManager$BaseBuffer cannot be cast to net.minecraft.class_527
    at customskinloader.fake.FakeSkinManager.loadSkin(FakeSkinManager.java:52)
    at customskinloader.fake.FakeSkinManager.loadSkin(FakeSkinManager.java:40)
    at net.minecraft.class_1885.handler$zco000$inject_loadSkin(class_1885.java:545)
    at net.minecraft.class_1885.method_7045(class_1885.java)
    at net.minecraft.class_1885.method_7044(class_1885.java:53)
    at net.minecraft.class_1359.method_10108(class_1359.java:78)
    at net.minecraft.class_2399.method_9772(class_2399.java:52)
    at net.minecraft.class_560.redirect$zfj000$onRender(class_560.java:1140)
    at net.minecraft.class_560.method_10243(class_560.java:122)
    at net.minecraft.class_560.method_10244(class_560.java:291)
    at net.minecraft.class_560.method_10245(class_560.java:269)
    at net.minecraft.class_529.method_9872(class_529.java:214)
    at net.minecraft.class_529.method_1354(class_529.java:493)
    at net.minecraft.class_524.method_1332(class_524.java:758)
    at net.minecraft.class_524.method_9776(class_524.java:1327)
    at net.minecraft.class_524.method_1326(class_524.java:1149)
    at net.minecraft.class_524.method_9775(class_524.java:1002)
    at net.minecraft.class_1600.method_2916(class_1600.java:915)
    at net.minecraft.class_1600.method_5580(class_1600.java:7057)
    at net.minecraft.client.main.Main.main(Main.java:124)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
    at oolloo.jlw.Wrapper.main(Wrapper.java:51)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [class_518['HowardZHY'/575, l='MpServer', x=-810.50, y=4.00, z=1759.50]]
    Chunk stats: MultiplayerChunkCache: 0, 0
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: -810.00,4.00,1768.00 - World: (-810,4,1768), Chunk: (at 6,0,8 in -51,110; contains blocks -816,0,1760 to -801,255,1775), Region: (-2,3; contains chunks -64,96 to -33,127, blocks -1024,0,1536 to -513,255,2047)
    Level time: 3 game time, 3 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [class_518['HowardZHY'/575, l='MpServer', x=-810.50, y=4.00, z=1759.50]]
    Retry entities: 0 total; []
    Server brand: fabric
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.class_478.method_4684(class_478.java:309)
    at net.minecraft.class_1600.method_2945(class_1600.java:2311)
    at net.minecraft.class_1600.method_5580(class_1600.java:7076)
    at net.minecraft.client.main.Main.main(Main.java:124)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
    at oolloo.jlw.Wrapper.main(Wrapper.java:51)
-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_311, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 144370360 bytes (137 MB) / 532152320 bytes (507 MB) up to 8500805632 bytes (8107 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8192m
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    Suspected Mods: CustomSkinLoader (customskinloader), Fabric Loader (fabricloader), Minecraft (minecraft)
    Fabric Mods: 
        axolotlclient: AxolotlClient 2.2.3-beta.1+1.8.9
        axolotlclientconfig: AxolotlClientConfig 1.0.12-beta.4+1.8.9
        com_github_jncrmx_discord-game-sdk4j: discord-game-sdk4j 0.5.5
        customskinloader: CustomSkinLoader 14.14-LF
        extendedhotbar: Extended Hotbar 1.0.0
        f3serverinfo: F3ServerInfo 1.0.1
        fabricloader: Fabric Loader 0.14.9
        java: Java HotSpot(TM) 64-Bit Server VM 8
        legacy-fabric-api: Legacy Fabric API 1.7.1
        legacy-fabric-api-base: Legacy Fabric API Base 1.1.0+1.8.9+f368a06d39
        legacy-fabric-api-base-common: Legacy Fabric API Base Common 1.1.0+common+1dd3cad892
        legacy-fabric-command-api-v1: Legacy Fabric Command API (V1) 1.0.0+common+ae4aa0d092
        legacy-fabric-command-api-v2: Legacy Fabric Command API (v2) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-crash-report-info-v1: Legacy Fabric Crash Report Info (v1) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-entity-events-v1: Legacy Fabric Entity Events (V1) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-entity-events-v1-common: Legacy Fabric Entity Events (V1) 1.0.0+common+ae4aa0d092
        legacy-fabric-fixes: Legacy Fabric Fixes 1.0.0+1.8.9+f368a06d39
        legacy-fabric-gamerule-api-v1: Fabric Gamerule API (v1) 1.0.0+common+ae4aa0d092
        legacy-fabric-item-groups-v1: Legacy Fabric Item Groups (V1) 2.0.0+1.8.9+f368a06d39
        legacy-fabric-item-groups-v1-common: Legacy Fabric Item Groups (V1) 2.0.0+common+1dd3cad892
        legacy-fabric-keybinding-api-v1-common: Legacy Fabric Keybinding API (V1) 1.0.0+common+ae4aa0d092
        legacy-fabric-lifecycle-events-v1: Legacy Fabric Lifecycle Events (V1) 1.0.1+1.8.9+d7cfcfda39
        legacy-fabric-lifecycle-events-v1-common: Legacy Fabric Lifecycle Events (V1) 1.0.1+common+ae4aa0d092
        legacy-fabric-logger-api-v1: Legacy Fabric Logger API (v1) 1.0.4+common+ae4aa0d092
        legacy-fabric-networking-api-v1: Legacy Fabric Networking API (v1) 2.0.0+1.8.9+f368a06d39
        legacy-fabric-networking-api-v1-common: Legacy Fabric Networking API (v1) 2.0.0+common+ae4aa0d092
        legacy-fabric-permissions-api-v1: Legacy Fabric Permissions API (v2) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-permissions-api-v1-common: Legacy Fabric Permissions API (v1) 1.0.0+common+ae4aa0d092
        legacy-fabric-registry-sync-api-v1: Legacy Fabric Registry Sync API (V1) 2.0.0+1.8.9+fc258ea839
        legacy-fabric-registry-sync-api-v1-common: Legacy Fabric Registry Sync API (V1) 2.0.0+common+5e222e4792
        legacy-fabric-rendering-api-v1: Legacy Fabric Rendering API (V1) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-rendering-api-v1-common: Legacy Fabric Rendering API (V1) 1.0.0+common+ae4aa0d092
        legacy-fabric-resource-loader-v1: Legacy Fabric Resource Loader (V1) 2.0.0+1.8.9+f368a06d39
        legacy-fabric-resource-loader-v1-common: Legacy Fabric Resource Loader (V1) Common 2.0.0+common+1dd3cad892
        legacyelytras: Legacy Elytras 1.1.0
        legacyinputpatch: LegacyInputPatch 1.8.9
        legacyvanillafix: Legacy VanillaFix 1.0.9+1.8.x
        minecraft: Minecraft 1.8.9
        net_hypixel_hypixel-api-core: hypixel-api-core 4.1
        net_hypixel_hypixel-api-transport-apache: hypixel-api-transport-apache 4.1
        org_yaml_snakeyaml: snakeyaml 1.31
        saltlib: SaltLib 0.2.0
        search-in-resources: Search in Resources 1.0.1
        tmi: TMI 1.8.9
        viabackwards: ViaBackwards 4.4.2
        viafabric: ViaFabric 0.4.9+19-main
        viafabric-mc18: ViaFabric for 1.8 0.4.9+19-main
        viarewind: ViaRewind 2.0.3-SNAPSHOT
        viaversion: ViaVersion 4.4.3-SNAPSHOT
    Launched Version: 1.8.9
    LWJGL: 2.9.4
    OpenGL: NVIDIA GeForce MX570/PCIe/SSE2 GL version 4.6.0 NVIDIA 526.47, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'AxolotlClient'
    Type: Client (map_client.txt)
    Resource Packs: 服务器自用
    Current Language: 简体中文 (中国)
    Profiler Position: N/A (disabled)
    CPU: 12x 12th Gen Intel(R) Core(TM) i7-1255U
    Client Crashes Since Restart: 2
    Integrated Server Crashes Since Restart: 0

**Comment by HowardZHY** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 2022-11-16 02:18:26 SGT
Description: Rendering Block Entity

java.lang.ClassCastException: customskinloader.fake.FakeSkinManager$BaseBuffer cannot be cast to net.minecraft.class_527
    at customskinloader.fake.FakeSkinManager.loadSkin(FakeSkinManager.java:52)
    at customskinloader.fake.FakeSkinManager.loadSkin(FakeSkinManager.java:40)
    at net.minecraft.class_1885.handler$zco000$inject_loadSkin(class_1885.java:545)
    at net.minecraft.class_1885.method_7045(class_1885.java)
    at net.minecraft.class_1885.method_7044(class_1885.java:53)
    at net.minecraft.class_1359.method_10108(class_1359.java:78)
    at net.minecraft.class_1359.method_4364(class_1359.java:38)
    at net.minecraft.class_1359.method_1631(class_1359.java:21)
    at net.minecraft.class_598.method_10100(class_598.java:114)
    at net.minecraft.class_598.method_10101(class_598.java:102)
    at net.minecraft.class_530.method_9908(class_530.java:615)
    at net.minecraft.class_524.method_9776(class_524.java:1244)
    at net.minecraft.class_524.method_1326(class_524.java:1149)
    at net.minecraft.class_524.method_9775(class_524.java:1002)
    at net.minecraft.class_1600.method_2916(class_1600.java:915)
    at net.minecraft.class_1600.method_5580(class_1600.java:7057)
    at net.minecraft.client.main.Main.main(Main.java:124)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
    at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block Entity Details --
Details:
    Name: minecraft:skull // net.minecraft.class_1311
    Block type: ID #144 (tile.skull // net.minecraft.class_1305)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (-75,68,-162), Chunk: (at 5,4,14 in -5,-11; contains blocks -80,0,-176 to -65,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Actual block type: ID #144 (tile.skull // net.minecraft.class_1305)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.class_598.method_10100(class_598.java:114)
    at net.minecraft.class_598.method_10101(class_598.java:102)
    at net.minecraft.class_530.method_9908(class_530.java:615)
    at net.minecraft.class_524.method_9776(class_524.java:1244)
    at net.minecraft.class_524.method_1326(class_524.java:1149)
-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [class_518['HowardZHY'/403, l='MpServer', x=-76.14, y=68.00, z=-161.27]]
    Chunk stats: MultiplayerChunkCache: 283, 283
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 0.00,64.00,0.00 - World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 22147 game time, 22147 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 90 total; [class_982['僵尸'/128, l='MpServer', x=-106.50, y=15.00, z=-135.50], class_951['鱿鱼'/129, l='MpServer', x=-105.63, y=62.47, z=-140.07], class_978['骷髅'/257, l='MpServer', x=-12.50, y=69.00, z=-142.50], class_1402['蝙蝠'/258, l='MpServer', x=0.56, y=30.72, z=-126.28], class_951['鱿鱼'/130, l='MpServer', x=-99.82, y=61.04, z=-103.51], class_1402['蝙蝠'/259, l='MpServer', x=-8.19, y=34.19, z=-122.44], class_943['鸡'/131, l='MpServer', x=-108.47, y=78.00, z=-92.94], class_943['鸡'/260, l='MpServer', x=-10.41, y=71.03, z=-127.88], class_982['僵尸'/261, l='MpServer', x=-5.47, y=80.00, z=-124.72], class_1402['蝙蝠'/274, l='MpServer', x=-5.44, y=32.91, z=-124.28], class_970['末影人'/412, l='MpServer', x=-155.50, y=28.00, z=-207.81], class_978['骷髅'/413, l='MpServer', x=-149.84, y=65.00, z=-194.50], class_978['骷髅'/414, l='MpServer', x=-136.50, y=32.00, z=-204.50], class_980['蜘蛛'/30, l='MpServer', x=-150.34, y=63.00, z=-166.22], class_964['item.item.seeds'/415, l='MpServer', x=-140.63, y=60.00, z=-205.56], class_982['僵尸'/31, l='MpServer', x=-150.75, y=64.00, z=-161.44], class_1402['蝙蝠'/417, l='MpServer', x=-113.53, y=42.10, z=-220.75], class_980['蜘蛛'/33, l='MpServer', x=-150.19, y=67.00, z=-126.72], class_944['牛'/162, l='MpServer', x=-81.50, y=67.00, z=-187.28], class_2623['兔子'/418, l='MpServer', x=-116.53, y=64.00, z=-205.53], class_949['羊'/34, l='MpServer', x=-156.91, y=66.00, z=-105.97], class_978['骷髅'/163, l='MpServer', x=-88.78, y=63.19, z=-144.13], class_978['骷髅'/164, l='MpServer', x=-85.47, y=63.06, z=-151.34], class_2623['兔子'/165, l='MpServer', x=-91.25, y=63.00, z=-134.38], class_2623['兔子'/421, l='MpServer', x=-102.22, y=63.00, z=-234.00], class_2623['兔子'/166, l='MpServer', x=-83.47, y=64.00, z=-129.69], class_951['鱿鱼'/422, l='MpServer', x=-107.87, y=59.16, z=-222.21], class_982['僵尸'/38, l='MpServer', x=-146.50, y=64.00, z=-90.50], class_2623['兔子'/423, l='MpServer', x=-106.19, y=63.00, z=-198.81], class_951['鱿鱼'/167, l='MpServer', x=-89.47, y=61.25, z=-113.16], class_2623['兔子'/168, l='MpServer', x=-90.84, y=63.00, z=-125.75], class_944['牛'/425, l='MpServer', x=-89.84, y=63.00, z=-210.16], class_951['鱿鱼'/169, l='MpServer', x=-91.86, y=61.03, z=-108.00], class_969['爬行者'/426, l='MpServer', x=-91.50, y=63.00, z=-217.50], class_943['鸡'/170, l='MpServer', x=-87.63, y=87.00, z=-84.41], class_980['蜘蛛'/427, l='MpServer', x=-87.75, y=63.00, z=-214.03], class_944['牛'/428, l='MpServer', x=-80.59, y=64.00, z=-201.03], class_944['牛'/429, l='MpServer', x=-80.81, y=64.00, z=-203.81], class_980['蜘蛛'/436, l='MpServer', x=-37.03, y=70.00, z=-218.72], class_2623['兔子'/437, l='MpServer', x=-38.47, y=88.00, z=-199.59], class_980['蜘蛛'/438, l='MpServer', x=-31.50, y=67.00, z=-231.50], class_2623['兔子'/439, l='MpServer', x=-21.50, y=73.00, z=-209.28], class_949['羊'/440, l='MpServer', x=-23.09, y=67.00, z=-223.88], class_978['骷髅'/56, l='MpServer', x=-139.25, y=64.00, z=-178.78], class_982['僵尸'/441, l='MpServer', x=-31.09, y=70.00, z=-215.53], class_969['爬行者'/57, l='MpServer', x=-142.94, y=61.00, z=-165.66], class_969['爬行者'/442, l='MpServer', x=-20.47, y=72.00, z=-208.00], class_982['僵尸'/58, l='MpServer', x=-143.44, y=60.00, z=-165.59], class_2623['兔子'/443, l='MpServer', x=-23.44, y=80.00, z=-207.13], class_1402['蝙蝠'/59, l='MpServer', x=-131.81, y=49.06, z=-169.63], class_2623['兔子'/444, l='MpServer', x=-26.41, y=88.31, z=-191.66], class_980['蜘蛛'/60, l='MpServer', x=-132.31, y=62.00, z=-150.97], class_969['爬行者'/61, l='MpServer', x=-132.97, y=64.00, z=-159.44], class_980['蜘蛛'/62, l='MpServer', x=-139.50, y=68.00, z=-122.50], class_943['鸡'/63, l='MpServer', x=-132.38, y=68.00, z=-122.34], class_978['骷髅'/64, l='MpServer', x=-141.06, y=21.00, z=-101.50], class_943['鸡'/65, l='MpServer', x=-139.53, y=62.41, z=-87.47], class_949['羊'/450, l='MpServer', x=-0.81, y=64.00, z=-228.13], class_943['鸡'/66, l='MpServer', x=-136.97, y=62.53, z=-87.59], class_949['羊'/451, l='MpServer', x=-14.09, y=71.00, z=-213.13], class_969['爬行者'/196, l='MpServer', x=-71.53, y=72.00, z=-174.03], class_2623['兔子'/452, l='MpServer', x=-15.78, y=71.00, z=-208.47], class_949['羊'/453, l='MpServer', x=-13.47, y=72.00, z=-204.34], class_969['爬行者'/209, l='MpServer', x=-51.34, y=86.00, z=-164.50], class_978['骷髅'/210, l='MpServer', x=-62.50, y=65.00, z=-120.03], class_978['骷髅'/211, l='MpServer', x=-63.44, y=63.00, z=-90.88], class_518['HowardZHY'/403, l='MpServer', x=-76.14, y=68.00, z=-161.27], class_978['骷髅'/221, l='MpServer', x=-46.16, y=88.00, z=-178.66], class_969['爬行者'/93, l='MpServer', x=-115.13, y=65.00, z=-191.31], class_943['鸡'/222, l='MpServer', x=-40.50, y=64.00, z=-146.81], class_982['僵尸'/94, l='MpServer', x=-123.84, y=64.00, z=-171.69], class_969['爬行者'/223, l='MpServer', x=-35.59, y=73.00, z=-151.06], class_964['item.item.egg'/224, l='MpServer', x=-39.59, y=64.00, z=-146.66], class_943['鸡'/96, l='MpServer', x=-127.63, y=62.66, z=-89.31], class_969['爬行者'/225, l='MpServer', x=-38.63, y=33.00, z=-125.00], class_978['骷髅'/226, l='MpServer', x=-33.59, y=65.00, z=-115.31], class_2623['兔子'/227, l='MpServer', x=-43.56, y=64.19, z=-126.63], class_982['僵尸'/236, l='MpServer', x=-16.06, y=57.00, z=-176.56], class_2623['兔子'/237, l='MpServer', x=-24.50, y=88.00, z=-182.75], class_943['鸡'/238, l='MpServer', x=-20.66, y=68.00, z=-144.47], class_964['item.item.egg'/239, l='MpServer', x=-23.00, y=67.00, z=-130.75], class_943['鸡'/240, l='MpServer', x=-27.38, y=63.00, z=-122.59], class_964['item.item.egg'/241, l='MpServer', x=-18.56, y=76.00, z=-125.09], class_1402['蝙蝠'/242, l='MpServer', x=-28.16, y=70.63, z=-128.72], class_982['僵尸'/243, l='MpServer', x=-26.75, y=88.00, z=-96.91], class_982['僵尸'/251, l='MpServer', x=-0.56, y=44.00, z=-189.94], class_2623['兔子'/252, l='MpServer', x=-4.72, y=79.00, z=-151.50], class_2623['兔子'/253, l='MpServer', x=-0.50, y=76.00, z=-153.59], class_2623['兔子'/254, l='MpServer', x=-15.94, y=69.00, z=-146.59], class_2623['兔子'/255, l='MpServer', x=-7.53, y=76.97, z=-142.47]]
    Retry entities: 0 total; []
    Server brand: fabric
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.class_478.method_4684(class_478.java:309)
    at net.minecraft.class_1600.method_2945(class_1600.java:2311)
    at net.minecraft.class_1600.method_5580(class_1600.java:7060)
    at net.minecraft.client.main.Main.main(Main.java:124)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
    at oolloo.jlw.Wrapper.main(Wrapper.java:51)
-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_311, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 118495576 bytes (113 MB) / 398458880 bytes (380 MB) up to 8500805632 bytes (8107 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8192m
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    Suspected Mods: CustomSkinLoader (customskinloader), Fabric Loader (fabricloader), Minecraft (minecraft)
    Fabric Mods: 
        axolotlclient: AxolotlClient 2.2.3-beta.1+1.8.9
        axolotlclientconfig: AxolotlClientConfig 1.0.12-beta.4+1.8.9
        com_github_jncrmx_discord-game-sdk4j: discord-game-sdk4j 0.5.5
        customskinloader: CustomSkinLoader 14.14-LF
        extendedhotbar: Extended Hotbar 1.0.0
        f3serverinfo: F3ServerInfo 1.0.1
        fabricloader: Fabric Loader 0.14.9
        java: Java HotSpot(TM) 64-Bit Server VM 8
        legacy-fabric-api: Legacy Fabric API 1.7.1
        legacy-fabric-api-base: Legacy Fabric API Base 1.1.0+1.8.9+f368a06d39
        legacy-fabric-api-base-common: Legacy Fabric API Base Common 1.1.0+common+1dd3cad892
        legacy-fabric-command-api-v1: Legacy Fabric Command API (V1) 1.0.0+common+ae4aa0d092
        legacy-fabric-command-api-v2: Legacy Fabric Command API (v2) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-crash-report-info-v1: Legacy Fabric Crash Report Info (v1) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-entity-events-v1: Legacy Fabric Entity Events (V1) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-entity-events-v1-common: Legacy Fabric Entity Events (V1) 1.0.0+common+ae4aa0d092
        legacy-fabric-fixes: Legacy Fabric Fixes 1.0.0+1.8.9+f368a06d39
        legacy-fabric-gamerule-api-v1: Fabric Gamerule API (v1) 1.0.0+common+ae4aa0d092
        legacy-fabric-item-groups-v1: Legacy Fabric Item Groups (V1) 2.0.0+1.8.9+f368a06d39
        legacy-fabric-item-groups-v1-common: Legacy Fabric Item Groups (V1) 2.0.0+common+1dd3cad892
        legacy-fabric-keybinding-api-v1-common: Legacy Fabric Keybinding API (V1) 1.0.0+common+ae4aa0d092
        legacy-fabric-lifecycle-events-v1: Legacy Fabric Lifecycle Events (V1) 1.0.1+1.8.9+d7cfcfda39
        legacy-fabric-lifecycle-events-v1-common: Legacy Fabric Lifecycle Events (V1) 1.0.1+common+ae4aa0d092
        legacy-fabric-logger-api-v1: Legacy Fabric Logger API (v1) 1.0.4+common+ae4aa0d092
        legacy-fabric-networking-api-v1: Legacy Fabric Networking API (v1) 2.0.0+1.8.9+f368a06d39
        legacy-fabric-networking-api-v1-common: Legacy Fabric Networking API (v1) 2.0.0+common+ae4aa0d092
        legacy-fabric-permissions-api-v1: Legacy Fabric Permissions API (v2) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-permissions-api-v1-common: Legacy Fabric Permissions API (v1) 1.0.0+common+ae4aa0d092
        legacy-fabric-registry-sync-api-v1: Legacy Fabric Registry Sync API (V1) 2.0.0+1.8.9+fc258ea839
        legacy-fabric-registry-sync-api-v1-common: Legacy Fabric Registry Sync API (V1) 2.0.0+common+5e222e4792
        legacy-fabric-rendering-api-v1: Legacy Fabric Rendering API (V1) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-rendering-api-v1-common: Legacy Fabric Rendering API (V1) 1.0.0+common+ae4aa0d092
        legacy-fabric-resource-loader-v1: Legacy Fabric Resource Loader (V1) 2.0.0+1.8.9+f368a06d39
        legacy-fabric-resource-loader-v1-common: Legacy Fabric Resource Loader (V1) Common 2.0.0+common+1dd3cad892
        legacyelytras: Legacy Elytras 1.1.0
        legacyinputpatch: LegacyInputPatch 1.8.9
        legacyvanillafix: Legacy VanillaFix 1.0.9+1.8.x
        minecraft: Minecraft 1.8.9
        net_hypixel_hypixel-api-core: hypixel-api-core 4.1
        net_hypixel_hypixel-api-transport-apache: hypixel-api-transport-apache 4.1
        org_yaml_snakeyaml: snakeyaml 1.31
        saltlib: SaltLib 0.2.0
        search-in-resources: Search in Resources 1.0.1
        tmi: TMI 1.8.9
        viabackwards: ViaBackwards 4.4.2
        viafabric: ViaFabric 0.4.9+19-main
        viafabric-mc18: ViaFabric for 1.8 0.4.9+19-main
        viarewind: ViaRewind 2.0.3-SNAPSHOT
        viaversion: ViaVersion 4.4.3-SNAPSHOT
    Launched Version: 1.8.9
    LWJGL: 2.9.4
    OpenGL: NVIDIA GeForce MX570/PCIe/SSE2 GL version 4.6.0 NVIDIA 526.47, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'AxolotlClient'
    Type: Client (map_client.txt)
    Resource Packs: 服务器自用
    Current Language: 简体中文 (中国)
    Profiler Position: N/A (disabled)
    CPU: 12x 12th Gen Intel(R) Core(TM) i7-1255U
    Client Crashes Since Restart: 1
    Integrated Server Crashes Since Restart: 0
